blueprint:
  name: Car presence
  description: Notify when car turns engine on by other person
  domain: automation
  input:
    car_location:
      name: Car location sensor
      description: Where is my car?
      selector:
        entity:
          domain: device_tracker
    person_location:
      name: Person location sensor
      description: Where am i?
      selector:
        entity:
          domain: device_tracker
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications
      selector:
        device:
          integration: mobile_app
    notification_title:
      name: Notification title (Optional)
      description: 'Default: "Car Warning"'
      default: "Car Warning"
    notification_message:
      name: Notification message (Optional)
      description: 'Default: "Someboby turn engine on"'
      default: "Someboby turn engine on"      

trigger:
  - platform: state
    entity_id: !input car_location
    
action:
  - service: notify.notify_device
    data:
      title: '{{ notification_title }}'
      message: '{{ notification_message }}'
      