blueprint:
  name: Car presence
  description: Notify when car turns engine on by other person
  domain: automation
  input:
    car_location:
      name: Car location sensor
      description: Where is my car?
      selector:
        entity:
          domain: device_tracker
    person_location:
      name: Person location sensor
      description: Where am i?
      selector:
        entity:
          domain: device_tracker
    engine_sensor:
      name: Car engine sensor
      description: Is turned on? 
      selector:
        entity:
          domain: binary_sensor           
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications
      selector:
        device:
          integration: mobile_app
    notification_title:
      name: Notification title (Optional)
      description: 'Default: "Car Warning"'
      default: "Car Warning"
    notification_message:
      name: Notification message (Optional)
      description: 'Default: "Somebody turn engine on"'
      default: "Somebody turn engine on"      

trigger:
  - platform: state
    entity_id: !input engine_sensor
    
action:
  domain: mobile_app
  type: notify
  device_id: !input notify_device
  title: !input notification_title
  message: !input notification_message

mode: single